name: aoc23
description: Advent of Code 2023.
version: 1.0.0
repository: https://github.com/mabdelaal86/adventofcode

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  basics: ^0.10.0
  quiver: ^3.2.1
  vector_math: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
